use_frameworks!

platform :ios, '8.0'

target 'SSLoadingAnimationAlert_Example' do
  pod 'SSLoadingAnimationAlert', :path => '../'

  target 'SSLoadingAnimationAlert_Tests' do
    inherit! :search_paths

    
  end
end
